language: node_js
node_js:
- 8
branches:
  only:
  - master
  - ft/ssl
before_install:
- npm install -g hexo-cli
- npm install
install:
- hexo generate
env:
  global:
    secure: UNdzoDBkVKnVnCD3225LI6YJUFOAL3b9hseJpStIzow8NQWDTOzwqW97yEhfT4stSQ/TpU36B4I9uRusjTX11NR1Vww8uBaVzCN1GUnY/xbvFsmAaZqrITtdBLzvf7NR0x4YPdh/j45Hrjmtsm4UnFy5OPuOgc1c40nzjD4PFPK22FF4VqlyTh5W/PMowhqCTqrgdP5gwYpZ0lwY0LnnpMPiZIZ4jU63QBHfIyQ981VOQTFBQZLEU3Rh3U2d8leDYYNR7RFF4V7E8PHlCiqxDV8lxLprrdabIkOk1B80IZo5dPslNE/GxTsy2It3P2OULNQuvM2HggPw3WBzU0nYVk5QyiduiIAK6LuRDubpq5NK9zLppIdLVERLb8bUdz1boDXSG+FFgGzQUVjN3GsEQ3LAmbOT1reJoM6B8xSyQDOge/+GkuEFtelFYjHWRvnADQvxAlbjgM6BrXy0AEtqncVir1uxHfFjLzS1ay/YDvYzwEPz2QAqQ8oH+oOAsElEDu/hC8asneamm95qxS5XEUEa+GmSUOOU5wib4hOrnPSmmEt2Ex4ZYPYUz3rTgp/FNatDZ076lSrm9VKMU8UWCRQBa8jyPjkV60xVCSeebw/pey/U2H8wQPL7GnpgWSr5Zc+uaMc3kw4sQkXHg42kXs835vE2uAnNyZlgqawEvd4=
notifications:
  slack:
    secure: WWadkpupU0eA0nGVm4yds4Jh8J4HYnktg61kj3tmzlUBR81ppEU2fDdXKoqQk3jAEP3b8bkT4UeVE+nvG8VZYyk4tMirWtwS0HeoIPeaZtUCe6Gg+Ff0xs92PTDCKAy/qS6UfENNVgdwQkOiSt/8IspDahZMBr0JSnTM014rrYSGME4ZMBauzKIBLxrWUNgXJ2Nhn4J7l2/rZGWpjG7OU5evMhSpIs+ikM/yYX0iI9d/4r8HA1Q2BLR0tXFjsLSGlDUeIpxUjatEO3C5+lp/xNnrMNNxNKLV7UoujCXtRPFYzh8e4CUM+cS8o3iDiQR4SxlJeD2lxcWejCNqptAQ8XMTax4VcFBr3H2x6m6Rv/1b2+amOM2nmA3U+XWVMwylUppm0IKyzMtKVxYBuK7O38CRT3nI+MFPFM9IxFYl8VXNYgX5NYmma5xOpBnMIqDmS8r5apxoRinLqUoDSXOSOIY4jiw4SUY9qHc2PHlHERsfL68JlIS2qljOu3hZjFE5mE/4GKaTA9R+2ZS3VZ2/w1QYqWxgmxL/YGTyVCuzCxnA94xIVTAc+D946ELczPkPW5hvEn7v4usKHXe4pfLQLIgFdVG+bjvNviaV6wrpWEEU+qQysuBx3vLu/VVgfeoZmMdE58h9gEf6QqqB2y0kZXS1AIsgnfo2NIOf7sRwqlE=
deploy:
  provider: s3
  access_key_id: AKIAIOMBR7GCTBR2TEXA
  secret_access_key:
    secure: aHMbg2z/JGQDdGY4T4Hjow6WwKG5dXutx4V0e11Lw8cEHAwSZ8uy8yLNWFA1+pZhh1m/tq0XEtqNnabq+ICalUQqCj3oX4m4+iiuzfVeI54qQ61LThUpBszgo2xOlDtMA5uQyJD+Xhz4iqZLZ4zHrncxn/UqQRQUEDLi5wYY5pDr0JAG71HtSQHEslPgNWOaR4B9/Ejb0MsWRoDFwS2dqUPtDymdPOvwP13MOOCrv716ln2+zNd2NvzVszHAGpWDyrDxfN6aKVJa8xQbwK0GfwSve1g/Pp8cBlSo3orDncYoKgZXZoJT9/A7IZ4d6Zg296bnkxHCFxB7WOqQoGpZjZEBjmR9cyAeKsWy/1klExtBUxAkzq/G0psh/0BpX6F6kzM4C3kPCc4p9+1k8pJ7my9gMgmIgM1jAfk+mUQmzx8hELVeouMw9rsjLiZsae9rNnClAt7pJ+5+Sf2EAIzF6VPHcODFYvuaQJHN75Xwrp+Emn83wXScn/gdCZKfG7SKoRbz0pY/f4U9SBLYk9Q+Jy45yrm0MnvQRbSiBUSVypGwMkLM6AN2mhNNu7kK++J8OlxKN2PORA8w+Gjyp0HkU6KL/v2hSzJ38wyXnhdSQOmUEsQ96iMZR/5hdFTAXXpANnCPYz1L94psigBYi8uT4RtzEEW7OPNwsjdgDjz4YBo=
  bucket: westerndevs.com
  region: ca-central-1
  skip_cleanup: true
  local-dir: public
  on:
    repo: westerndevs/western-devs-website
    branch: ft/ssl
