name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build
    - name: Deploy PR to Test Site
      if: github.event_name == 'pull_request'
      run: |
        git config --global user.email "wd@westerndevs.com"
        git config --global user.name "Western Devs"
        git branch pr-temp
        git add .
        git commit -m "Publishing PR for testing"
        git remote add testing https://dylan-smith:${{ secrets.TESTING_TOKEN }}@github.com/dylan-smith/wd-test.git
        git push testing gh-pages
      
