name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build
    - name: Deploy PR to Test Site
      if: github.event_name == 'pull_request'
      run: |
        mkdir /home/runner/temp_publish
        git clone --depth=1 --single-branch --branch gh-pages https://dylan-smith:${{ secrets.TESTING_TOKEN }}@github.com/dylan-smith/wd-test.git /home/runner/temp_publish
        cd /home/runner/temp_publish
        git rm -r --ignore-unmatch *
        cp /home/runner/work/western-devs-website/western-devs-website/public /home/runner/temp_publish
        git remote rm origin
        git remote add origin https://dylan-smith:${{ secrets.TESTING_TOKEN }}@github.com/dylan-smith/wd-test.git
        git add --all
        git config user.email "wd@westerndevs.com"
        git config user.name "Western Devs"
        git commit -m "publishing PR for testing"
        git push origin gh-pages
      
