name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build
    - name: Deploy to Test Site
      if: github.event_name == 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: dylan-smith/wd-test
        personal_token: ${{ secrets.TESTING_TOKEN }}
        commit_message: ${{ github.event.head_commit.message }}
        exclude_assets: 'CNAME'
      
