name: CI/CD
on:
  push:
    branches:
      - master
      - ft/*
      - hf/*

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule init
        git submodule update --remote --merge
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 14
    - run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: website
        path: public/
  publish:
    name: Publish Website
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: website
          path: website
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
          cname: www.westerndevs.com
          commit_message: ${{ github.event.head_commit.message }}


 
      